language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_install:
    - composer self-update --1

install:
    - composer install

script:
    - php vendor/bin/parallel-lint ./src
    - php vendor/bin/ecs check --verbose ./src
